version: '3'

services:
  tornginx:
    build: .
    restart: always
    ports:
      - 127.0.0.1:9050:9050
    volumes:
      - ./tor-config:/etc/tor:Z
      - ./tor-data:/var/lib/tor:Z
      - ./logs:/var/log/tor:Z
      - ./nginx-config:/etc/nginx/sites-enabled:Z
      - ./web-public:/var/www/html:Z
