name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Read current version
        id: get_version
        run: echo "::set-output name=current_version::$(cat VERSION)"

      - name: Increment version
        id: increment_version
        run: |
          version=$(echo "${{ steps.get_version.outputs.current_version }}" | awk -F. '{printf("%d.%d.%d", $1, $2, $3+1)}')
          echo "New version: $version"
          echo $version > VERSION
          echo "::set-output name=new_version::$version"

      - name: Commit and push new version
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git commit -m "Increment version to ${{ steps.increment_version.outputs.new_version }}"
          git push origin HEAD:main

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/tor-website:${{ steps.increment_version.outputs.new_version }}
